# Guide Numpy

A travers ce guide nous verons les fonctions les plus utiles de numpy. <br>
La librarie numpy est très utilisé pour la création et la manipulation de vecteurs avec python.


In [0]:
import numpy as np

# Création de vecteurs

Plusieur fonction utiles pour créer des vecteurs

In [0]:
# Création d'un vecteur
>>> np.array([[1,2],[5,6]])
array([[1, 2],
       [5, 6]])

# Création d'un vecteur composé de 0
>>> np.zeros((2,2))
array([[0., 0.],
       [0., 0.]])

# Création d'un vecteur composé de 1
>>> np.ones((2,2))
array([[1., 1.],
       [1., 1.]])

# Création d'un vecteur composé d'une range de valeur
>>> np.arange(start = 1, stop = 4, step = 1)
array([1, 2, 3])

# Création d'un vecteur composé de 5 nombres entre 1 et 0 à interval régulier 
>>> np.linspace(0,1,5)
array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Création d'un vecteur de n nombre aléatoire entre 0 et 1
>>> np.random.random((2,2))
array([[0.62420147, 0.32848398],
       [0.59501749, 0.49543965]])

# Création d'un vecteur de n nombres générés aléatoirement celon une loi normal 
>>> np.random.randn(2)
array([0.8738856 , 1.17466123])

# Création d'un vecteur de n nombres entier aléatoire entre min et max
>>> np.random.randint(1, 10, 5)
array([8, 2, 7, 6, 9])

# Créer une matrice identité
>>> np.eye(3,3)
#array([[1., 0., 0.],
#       [0., 1., 0.],
#       [0., 0., 1.]])


## Informations sur un vecteur

In [0]:
vect = np.random.random((2,2))

In [0]:
# Optenir la shape du vecteur
>>> vect.shape
(2, 2)

# Obtenir le format du vecteur
>>> vect.dtype
dtype('float64')

# Obtenir le nombre de dimmenssion
>>> vect.ndim
2

# Obtenir la taille du vecteur
>>> vect.size
4

# Manipuation de vecteur

In [0]:
vect = np.random.random((2,2))
vect 

array([[0.87159346, 0.31201421],
       [0.34451705, 0.44297274]])

In [0]:
# Modification du format du vecteur
>>> vect.astype(int)
array([[0, 0],
       [0, 0]])

# Trier le vecteur par la dimmention selectionné
>>> np.sort(vect, axis = 0)
array([[0.16140848, 0.64891121],
       [0.45412182, 0.78870194]])

# Ajouter un vecteur à un autre vecteur
>>> np.append(vect,vect[:1])
array([0.45412182, 0.64891121, 0.16140848, 0.78870194, 0.45412182, 0.64891121])

# Extraire une partie d'un vecteur
>>> vect.reshape((1,-1))
array([[0.45412182, 0.64891121, 0.16140848, 0.78870194]])

# Concatenation de deux vecteurs
>>> np.concatenate((vect,vect),axis=0)
array([[0.45412182, 0.64891121],
       [0.16140848, 0.78870194],
       [0.45412182, 0.64891121],
       [0.16140848, 0.78870194]])

# Divise un vecteur en plusieur sous-vecteur
>>> vect1, vect2 = np.array_split(vect, 2)
>>> print(vect1)
>>> print(vect2)
[[0.45412182 0.64891121]]
[[0.16140848 0.78870194]]

# Applati un vecteur en 1 dimenssion (revient au même que vect.reshape(-1))
>>> vect.flatten()
array([0.45412182, 0.64891121, 0.16140848, 0.78870194])

# Transposition d'un vecteur
>>> vect.transpose()
array([[0.45412182, 0.16140848],
       [0.64891121, 0.78870194]])

# Inversion de matrice
>>> np.linalg.inv(vect)
array([[ 3.11214662, -2.56054505],
       [-0.6369033 ,  1.79192371]])


## Opération sur les vecteurs

In [0]:
# Adition de deux vecteurs
>>> np.add(vect,vect)
array([[0.50823531, 0.92420162],
       [0.55160466, 0.24786462]])

# Soustraction de deux vecteurs
>>> np.subtract(vect,vect)
array([[0., 0.],
       [0., 0.]])

# Division de deux vecteurs
>>> np.divide(vect,vect)
array([[1., 1.],
       [1., 1.]])

# Multiplication de deux vecteurs 
>>> np.multiply(vect,vect)
array([[0.06457578, 0.21353716],
       [0.07606693, 0.01535922]])

# Produits scalaire de 2 matrices
>>> np.dot(vect,vect)
array([[0.19202426, 0.17469719],
       [0.10426706, 0.1428077 ]])

# Teste l'egalité entre deux vecteurs
>>> np.equal(vect,vect)
array([[ True,  True],
       [ True,  True]])

# passe chaque valeurs a la racine carré
>>> np.sqrt(vect)
array([[0.50410084, 0.67977997],
       [0.52516886, 0.35204021]])

# passe chaque valeurs au sinus
>>> np.sin(vect)
array([[0.2513915 , 0.44582956],
       [0.27231903, 0.1236153 ]])

# passe chaque valeurs au cosinus
>>> np.cos(vect)
array([[0.96788549, 0.89511787],
       [0.96220702, 0.99233022]])

# passe chaque valeurs au log
>>> np.log(vect)
array([[-1.36995791, -0.77197221],
       [-1.28807086, -2.08801976]])

## Agrégation

In [0]:
# Somme d'un vecteur
>>> np.sum(vect)
1.4661173044858296

# Minimum d'un vecteur
>>> np.min(vect)
0.007704675895379376

# Indice du minimum
>>> np.argmin(vect)
0

# Indice des minimum pour la dimention axis
>>> np.argmin(vect,axis=0)
array([1, 0])

# Maximum d'un vecteur 
>>> np.max(vect)
0.8240497812697638

# Indice du maximum
>>> np.argmax(vect)
1

# Ecart type d'un vecteur
>>> np.std(vect)
0.29823842159783637

# Somme cumulé d'un vecteur
>>> np.cumsum(vect)
 array([0.00770468, 0.83175446, 1.0688294 , 1.4661173 ])

# Coeficient de corrélation
>>> vect = np.random.random((3,1000))
>>> np.corrcoef(vect)
array([[ 1.        ,  0.02158884,  0.00444511],
       [ 0.02158884,  1.        , -0.03100398],
       [ 0.00444511, -0.03100398,  1.        ]])